### ISSUE TITLE
Issues to move to r2dii.analysis?

### ISSUE THREAD

**Issue by maurolepore** [RMI-PACTA/r2dii.analysis#311]
Putting this here because it comes form the focused feedback we got via
the googledoc.

George said:

(1) For the SDA plot it should be
    - Corporate economy Actual 
    - Portfolio Actual 
    - Portfolio Target 
    - Corporate economy target

(2) Perhaps we could align "projected" with "portfolio"

If I understand correctly these are values all in columns that come from
r2dii.analysis, so I think this issue shold be reported there not here.

ideas?

**Comment by jdhoffa** [comment]
Superseded by #469 and #470
