### ISSUE TITLE
post-CRAN-acceptance (0.3.0) Follow-up tasks

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/r2dii.analysis#448]
Following the closure of #447, there are some tasks in #444 that still need to be finished after acceptance to CRAN.

- [x] Accepted 🎉
- [ ] Add preemptive link to blog post in pkgdown news menu
- [x] `usethis::use_github_release()`
- [x] `usethis::use_dev_version(push = TRUE)`
- [ ] Finish & Publish blog post

**Comment by jdhoffa** [comment]
Any progress on this?

**Comment by AlexAxthelm** [comment]
@jdhoffa Like the rest of the r2dii.* packages, I jumped straight into a different fire after it was all on CRAN and never came back to these. You might be in a better position to write up a blog post than me.

**Comment by jdhoffa** [comment]
Awesome thanks will do! Looking for issues to tackle in `r2dii` so seems like post CRAN stuff is a good place to start.

**Comment by jdhoffa** [comment]
Closed by #451 (minus the blog post, but we don't do those for packages right now anyway... can consider this in the future)
